apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstoneproject
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
        - image: ahmedadelelshorafa/capstoneproject
          imagePullPolicy: Always
          name: capstoneproject
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject
  labels:
    app: capstoneproject
spec:
  type: LoadBalancer
  selector:
    app: capstoneproject
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
