version: 2.1

jobs:
  Testing HTML Validity:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Testing HTML Validity
          command: |
            sudo apt-get install tidy -y
            tidy -q -e *.html
   Building Docker Image: 
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Docker-configuration
          command: |
            docker login -u ${DOCKER_ID} -p ${DOCKER_PASSWORD}
            docker build -t ahmedadelelshorafa/capstoneproject .
            docker push ahmedadelelshorafa/capstoneproject
workflows:
  deployment:
    jobs:
      - Testing HTML Validity
      - Building Docker Image:
          requires:
            - "Testing HTML Validity"
