version: 2.1

jobs:
  Testing HTML Validity:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Testing HTML Validity
          command: |
            sudo apt-get install tidy -y
            tidy -q -e *.html
  Building Docker Image: 
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Docker-configuration
          command: |
            docker login -u ${DOCKER_ID} -p ${DOCKER_PASSWORD}
            docker build -t ahmedadelelshorafa/capstoneproject .
            docker push ahmedadelelshorafa/capstoneproject
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          capstone
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/capstoneproject
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          capstone
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
  Switch Deployment:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deleting previous Deployment
          command: |
            aws ec2 terminate-instances --instance-ids  i-0ec5bb8fff9de43d9          
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2            
            
workflows:
  deployment:
    jobs:
      - Testing HTML Validity
      - Building Docker Image:
          requires:
            - "Testing HTML Validity"
      - aws-eks/create-cluster:
          cluster-name: capstoneproject3
      - create-deployment:
          cluster-name: capstoneproject3
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          cluster-name: capstoneproject3
          container-image-updates: capstoneproject=ahmedadelelshorafa/capstoneproject
          post-steps:
              - kubernetes/delete-resource:
                  resource-names: capstoneproject
                  resource-types: deployment
                  wait: true
          record: true
          requires:
              - create-deployment
          resource-name: deployment/capstoneproject
      - test-cluster:
          cluster-name: capstoneproject3
          requires:
            - aws-eks/update-container-image   
      - Switch Deployment:
          requires:
            - test-cluster              
